In [1]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/kagglex/final_used_price.csv
/kaggle/input/kagglex/test.csv
/kaggle/input/kagglex/final_train.csv

In [4]:
from autogluon.tabular import TabularDataset, TabularPredictor

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import category_encoders as ce
from sklearn.preprocessing import RobustScaler

In [8]:
train = pd.read_csv('/kaggle/input/kagglex/final_train.csv')
train.head(2)

  brand  milage fuel_type  transmission  accident  price     HP  Volume  age
0  Ford   74349  Gasoline  10-Speed A/T         0  11000  375.0     3.5    6
1   BMW   80000  Gasoline   6-Speed M/T         0   8250  300.0     3.0   17

In [10]:
original = pd.read_csv('/kaggle/input/kagglex/final_used_price.csv')
original.head(2)

,brand,milage,fuel_type,transmission,accident,price,HP,Volume,age
0,Ford,51000.0,E85 Flex Fuel,6-Speed A/T,1,10300.0,300.0,3.7,11
1,Hyundai,34742.0,Gasoline,8-Speed Automatic,1,38005.0,NaN,3.8,3

In [11]:
the_train = pd.concat([train, original], ignore_index=True)
the_train.head(2)

,brand,milage,fuel_type,transmission,accident,price,HP,Volume,age
0,Ford,74349.0,Gasoline,10-Speed A/T,0,11000.0,375.0,3.5,6
1,BMW,80000.0,Gasoline,6-Speed M/T,0,8250.0,300.0,3.0,17

In [12]:
len(train), len(original), len(the_train)

(54273, 4009, 58282)

In [14]:
test = pd.read_csv('/kaggle/input/kagglex/test.csv')
test.head(2)

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title
0,54273,Mercedes-Benz,E-Class E 350,2014,73000,Gasoline,302.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,White,Beige,None reported,Yes
1,54274,Lexus,RX 350 Base,2015,128032,Gasoline,275.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,8-Speed A/T,Silver,Black,None reported,Yes

In [16]:
kaggle_ids = test['id']
kaggle_ids

0        54273
1        54274
2        54275
3        54276
4        54277
         ...
36178    90451
36179    90452
36180    90453
36181    90454
36182    90455
Name: id, Length: 36183, dtype: int64

In [17]:
test.drop(columns=['id','model','ext_col','int_col','clean_title'], inplace=True)
test.head(2)

,brand,model_year,milage,fuel_type,engine,transmission,accident
0,Mercedes-Benz,2014,73000,Gasoline,302.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,None reported
1,Lexus,2015,128032,Gasoline,275.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,8-Speed A/T,None reported

In [18]:
hp_pattern = '(\d+(?:\.\d+))HP'
def extract_hp(text):
    matches = re.findall(hp_pattern, text)
    return float(matches[0]) if matches else np.nan

vol_pattern = '(\d+(?:\.\d+))L'
def extract_vol(text):
    matches = re.findall(vol_pattern, text)
    return float(matches[0]) if matches else np.nan

test['HP'] = test['engine'].apply(extract_hp)
test['Volume'] = test['engine'].apply(extract_vol)

test.drop(columns=['engine'], inplace=True)

In [19]:
test.head()

,brand,model_year,milage,fuel_type,transmission,accident,HP,Volume
0,Mercedes-Benz,2014,73000,Gasoline,A/T,None reported,302.0,3.5
1,Lexus,2015,128032,Gasoline,8-Speed A/T,None reported,275.0,3.5
2,Mercedes-Benz,2015,51983,Gasoline,7-Speed A/T,None reported,241.0,2.0
3,Land,2018,29500,Gasoline,Transmission w/Dual Shift Mode,At least 1 accident or damage reported,518.0,5.0
4,BMW,2020,90000,Gasoline,8-Speed A/T,At least 1 accident or damage reported,335.0,3.0

In [20]:
test['age'] = 2024 - test['model_year']
test.drop(columns=['model_year'], inplace=True)

In [21]:
test['accident'].value_counts()

accident
None reported                             26598
At least 1 accident or damage reported     9585
Name: count, dtype: int64

In [22]:
acc_pattern = 'None'
def accident(text):
    matches = re.findall(acc_pattern, text)
    if matches:
        return 0
    else:
        return 1

test['accident'] = test['accident'].apply(accident)

In [23]:
test.head(2)

           brand  milage fuel_type transmission  accident     HP  Volume  age
0  Mercedes-Benz   73000  Gasoline          A/T         0  302.0     3.5   10
1          Lexus  128032  Gasoline  8-Speed A/T         0  275.0     3.5    9

In [24]:
manual_pattern = 'M/T|Manual|Mt|Fixed'
dual_pattern = 'Dual|At/Mt|2'

def ismanual(text):
    match1 = re.findall(manual_pattern, text)
    if(match1):
        return 1
    match2 = re.findall(dual_pattern, text)
    if(match2):
        return 1
    return 0

def isauto(text):
    match1 = re.findall(manual_pattern, text)
    if(match1):
        return 0
    else:
        return 1

the_train['is_auto'] = the_train['transmission'].apply(isauto)
the_train['is_manual'] = the_train['transmission'].apply(ismanual)

test['is_auto'] = test['transmission'].apply(isauto)
test['is_manual'] = test['transmission'].apply(ismanual)

In [25]:
target_encoder = ce.TargetEncoder(cols=['transmission'])
the_train['transmission'] = target_encoder.fit_transform(the_train['transmission'], the_train['price'])
test['transmission'] = target_encoder.transform(test['transmission'])

In [26]:
the_train.head(2)

,brand,milage,fuel_type,transmission,accident,price,HP,Volume,age,is_auto,is_manual
0,Ford,74349.0,Gasoline,60529.132264,0,11000.0,375.0,3.5,6,1,0
1,BMW,80000.0,Gasoline,34274.547594,0,8250.0,300.0,3.0,17,0,1

In [27]:
test.head(2)

,brand,milage,fuel_type,transmission,accident,HP,Volume,age,is_auto,is_manual
0,Mercedes-Benz,73000,Gasoline,30060.575756,0,302.0,3.5,10,1,0
1,Lexus,128032,Gasoline,52428.890420,0,275.0,3.5,9,1,0

In [28]:
def cap_outliers_price(df, col='price'):
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3-Q1
    lower_bound = Q1 - (1.5*IQR)
    upper_bound = Q3 + (1.5*IQR)
    df[col] = df[col].apply(lambda x: lower_bound if x<lower_bound else upper_bound if x>upper_bound else x)
    return df, lower_bound, upper_bound

In [29]:
the_train, lb, ub = cap_outliers_price(the_train)
lb, ub

(-29041.5, 90802.5)

In [30]:
the_train['price'].max(), the_train['price'].min()

(90802.5, 2000.0)

In [31]:
the_train.isnull().sum()

brand              0
milage            55
fuel_type          0
transmission       0
accident           0
price              0
HP              4867
Volume          1002
age                0
is_auto            0
is_manual          0
dtype: int64

In [32]:
milage_median = the_train['milage'].median()
hp_median = the_train['HP'].median()
vol_median = the_train['Volume'].median()

the_train['milage'].fillna(milage_median, inplace=True)
the_train['HP'].fillna(hp_median, inplace=True)
the_train['Volume'].fillna(vol_median, inplace=True)

/tmp/ipykernel_34/3032000244.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  the_train['milage'].fillna(milage_median, inplace=True)
/tmp/ipykernel_34/3032000244.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  the_train['HP'].fillna(hp_median, inplace=True)
/tmp/ipykernel_34/3032000244.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  the_train['Volume'].fillna(vol_median, inplace=True)

In [33]:
the_train.isnull().sum()

brand           0
milage          0
fuel_type       0
transmission    0
accident        0
price           0
HP              0
Volume          0
age             0
is_auto         0
is_manual       0
dtype: int64

In [34]:
test.isnull().sum()

brand              0
milage             0
fuel_type          0
transmission       0
accident           0
HP              2606
Volume           405
age                0
is_auto            0
is_manual          0
dtype: int64

In [35]:
hp_median = test['HP'].median()
vol_median = test['Volume'].median()

test['HP'].fillna(hp_median, inplace=True)
test['Volume'].fillna(vol_median, inplace=True)

/tmp/ipykernel_34/4237268345.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test['HP'].fillna(hp_median, inplace=True)
/tmp/ipykernel_34/4237268345.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test['Volume'].fillna(vol_median, inplace=True)

In [36]:
test.isnull().sum()

brand           0
milage          0
fuel_type       0
transmission    0
accident        0
HP              0
Volume          0
age             0
is_auto         0
is_manual       0
dtype: int64

In [37]:
the_train.head(2)

,brand,milage,fuel_type,transmission,accident,price,HP,Volume,age,is_auto,is_manual
0,Ford,74349.0,Gasoline,60529.132264,0,11000.0,375.0,3.5,6,1,0
1,BMW,80000.0,Gasoline,34274.547594,0,8250.0,300.0,3.0,17,0,1

In [38]:
the_train['fuel_type'].value_counts()

fuel_type
Gasoline          52918
Hybrid             1960
E85 Flex Fuel      1618
Diesel             1225
Electric            345
Plug-In Hybrid      216
Name: count, dtype: int64

In [39]:
test['fuel_type'].value_counts()

fuel_type
Gasoline          33033
Hybrid             1112
E85 Flex Fuel      1018
Diesel              671
–                   197
Plug-In Hybrid      148
not supported         4
Name: count, dtype: int64

In [41]:
test['fuel_type'] = test['fuel_type'].apply(lambda x: 'Electric' if x=='–' else 'Electric' if x=='not supported' else x)

In [42]:
test['fuel_type'].value_counts()

fuel_type
Gasoline          33033
Hybrid             1112
E85 Flex Fuel      1018
Diesel              671
Electric            201
Plug-In Hybrid      148
Name: count, dtype: int64

In [43]:
cols = ['brand', 'fuel_type']
the_train = pd.get_dummies(the_train, columns=cols, prefix=cols, dummy_na=False, dtype=float)
test = pd.get_dummies(test, columns=cols, prefix=cols, dummy_na=False, dtype=float)

In [44]:
test.insert(test.columns.get_loc('brand_Jeep') + 1, 'brand_Karma', 0)
test.insert(test.columns.get_loc('brand_Maserati') + 1, 'brand_Maybach', 0)
test.insert(test.columns.get_loc('brand_Nissan') + 1, 'brand_Plymouth', 0)
test.insert(test.columns.get_loc('brand_Plymouth') + 1, 'brand_Polestar', 0)

In [46]:
pd.set_option('display.max_columns', None)
the_train.head(2)

,milage,transmission,accident,price,HP,Volume,age,is_auto,is_manual,brand_Acura,brand_Alfa,brand_Aston,brand_Audi,brand_BMW,brand_Bentley,brand_Bugatti,brand_Buick,brand_Cadillac,brand_Chevrolet,brand_Chrysler,brand_Dodge,brand_FIAT,brand_Ferrari,brand_Ford,brand_GMC,brand_Genesis,brand_Honda,brand_Hummer,brand_Hyundai,brand_INFINITI,brand_Jaguar,brand_Jeep,brand_Karma,brand_Kia,brand_Lamborghini,brand_Land,brand_Lexus,brand_Lincoln,brand_Lotus,brand_Lucid,brand_MINI,brand_Maserati,brand_Maybach,brand_Mazda,brand_McLaren,brand_Mercedes-Benz,brand_Mercury,brand_Mitsubishi,brand_Nissan,brand_Plymouth,brand_Polestar,brand_Pontiac,brand_Porsche,brand_RAM,brand_Rivian,brand_Rolls-Royce,brand_Saab,brand_Saturn,brand_Scion,brand_Subaru,brand_Suzuki,brand_Tesla,brand_Toyota,brand_Volkswagen,brand_Volvo,brand_smart,fuel_type_Diesel,fuel_type_E85 Flex Fuel,fuel_type_Electric,fuel_type_Gasoline,fuel_type_Hybrid,fuel_type_Plug-In Hybrid
0,74349.0,60529.132264,0,11000.0,375.0,3.5,6,1,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,80000.0,34274.547594,0,8250.0,300.0,3.0,17,0,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [47]:
test.head(2)

,milage,transmission,accident,HP,Volume,age,is_auto,is_manual,brand_Acura,brand_Alfa,brand_Aston,brand_Audi,brand_BMW,brand_Bentley,brand_Bugatti,brand_Buick,brand_Cadillac,brand_Chevrolet,brand_Chrysler,brand_Dodge,brand_FIAT,brand_Ferrari,brand_Ford,brand_GMC,brand_Genesis,brand_Honda,brand_Hummer,brand_Hyundai,brand_INFINITI,brand_Jaguar,brand_Jeep,brand_Karma,brand_Kia,brand_Lamborghini,brand_Land,brand_Lexus,brand_Lincoln,brand_Lotus,brand_Lucid,brand_MINI,brand_Maserati,brand_Maybach,brand_Mazda,brand_McLaren,brand_Mercedes-Benz,brand_Mercury,brand_Mitsubishi,brand_Nissan,brand_Plymouth,brand_Polestar,brand_Pontiac,brand_Porsche,brand_RAM,brand_Rivian,brand_Rolls-Royce,brand_Saab,brand_Saturn,brand_Scion,brand_Subaru,brand_Suzuki,brand_Tesla,brand_Toyota,brand_Volkswagen,brand_Volvo,brand_smart,fuel_type_Diesel,fuel_type_E85 Flex Fuel,fuel_type_Electric,fuel_type_Gasoline,fuel_type_Hybrid,fuel_type_Plug-In Hybrid
0,73000,30060.575756,0,302.0,3.5,10,1,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,1.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,128032,52428.890420,0,275.0,3.5,9,1,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [48]:
cols = ['milage','transmission','HP','Volume','age']
sc = RobustScaler()
train_sc = sc.fit_transform(the_train[cols])
the_train['milage']=train_sc[:, 0]
the_train['transmission']=train_sc[:, 1]
the_train['HP']=train_sc[:, 2]
the_train['Volume']=train_sc[:, 3]
the_train['age']=train_sc[:, 4]

In [49]:
the_train.head(2)

,milage,transmission,accident,price,HP,Volume,age,is_auto,is_manual,brand_Acura,brand_Alfa,brand_Aston,brand_Audi,brand_BMW,brand_Bentley,brand_Bugatti,brand_Buick,brand_Cadillac,brand_Chevrolet,brand_Chrysler,brand_Dodge,brand_FIAT,brand_Ferrari,brand_Ford,brand_GMC,brand_Genesis,brand_Honda,brand_Hummer,brand_Hyundai,brand_INFINITI,brand_Jaguar,brand_Jeep,brand_Karma,brand_Kia,brand_Lamborghini,brand_Land,brand_Lexus,brand_Lincoln,brand_Lotus,brand_Lucid,brand_MINI,brand_Maserati,brand_Maybach,brand_Mazda,brand_McLaren,brand_Mercedes-Benz,brand_Mercury,brand_Mitsubishi,brand_Nissan,brand_Plymouth,brand_Polestar,brand_Pontiac,brand_Porsche,brand_RAM,brand_Rivian,brand_Rolls-Royce,brand_Saab,brand_Saturn,brand_Scion,brand_Subaru,brand_Suzuki,brand_Tesla,brand_Toyota,brand_Volkswagen,brand_Volvo,brand_smart,fuel_type_Diesel,fuel_type_E85 Flex Fuel,fuel_type_Electric,fuel_type_Gasoline,fuel_type_Hybrid,fuel_type_Plug-In Hybrid
0,0.133082,1.17374,0,11000.0,0.511811,0.0000,-0.285714,1,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,0.213523,0.00000,0,8250.0,-0.078740,-0.3125,1.285714,0,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [50]:
test_sc = sc.transform(test[cols])
test['milage']=test_sc[:, 0]
test['transmission']=test_sc[:, 1]
test['HP']=test_sc[:, 2]
test['Volume']=test_sc[:, 3]
test['age']=test_sc[:, 4]

In [51]:
test.head(2)

,milage,transmission,accident,HP,Volume,age,is_auto,is_manual,brand_Acura,brand_Alfa,brand_Aston,brand_Audi,brand_BMW,brand_Bentley,brand_Bugatti,brand_Buick,brand_Cadillac,brand_Chevrolet,brand_Chrysler,brand_Dodge,brand_FIAT,brand_Ferrari,brand_Ford,brand_GMC,brand_Genesis,brand_Honda,brand_Hummer,brand_Hyundai,brand_INFINITI,brand_Jaguar,brand_Jeep,brand_Karma,brand_Kia,brand_Lamborghini,brand_Land,brand_Lexus,brand_Lincoln,brand_Lotus,brand_Lucid,brand_MINI,brand_Maserati,brand_Maybach,brand_Mazda,brand_McLaren,brand_Mercedes-Benz,brand_Mercury,brand_Mitsubishi,brand_Nissan,brand_Plymouth,brand_Polestar,brand_Pontiac,brand_Porsche,brand_RAM,brand_Rivian,brand_Rolls-Royce,brand_Saab,brand_Saturn,brand_Scion,brand_Subaru,brand_Suzuki,brand_Tesla,brand_Toyota,brand_Volkswagen,brand_Volvo,brand_smart,fuel_type_Diesel,fuel_type_E85 Flex Fuel,fuel_type_Electric,fuel_type_Gasoline,fuel_type_Hybrid,fuel_type_Plug-In Hybrid
0,0.113879,-0.18839,0,-0.062992,0.0,0.285714,1,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,1.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,0.897253,0.81161,0,-0.275591,0.0,0.142857,1,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [52]:
target='price'
gluon_automl = TabularPredictor(label=target, eval_metric='root_mean_squared_error').fit(the_train, presets='best_quality')

No path specified. Models will be saved in: "AutogluonModels/ag-20240623_082907"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.1.1
Python Version:     3.10.13
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Tue Dec 19 13:14:11 UTC 2023
CPU Count:          4
Memory Avail:       29.55 GB / 31.36 GB (94.2%)
Disk Space Avail:   19.50 GB / 19.52 GB (99.9%)
===================================================
Presets specified: ['best_quality']
Setting dynamic_stacking from 'auto' to True. Reason: Enable dynamic_stacking when use_bag_holdout is disabled. (use_bag_holdout=False)
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=8, num_bag_sets=1
DyStack is enabled (dynamic_stacking=True). AutoGluon will try to determine whether the input data is affected by stacked overfitting and enable or disable stacking as a consequence.
	This is used to identify the optimal `num_stack_levels` value. Copies of AutoGluon will be fit on subsets of the data. Then holdout validation data is used to detect stacked overfitting.
	Running DyStack for up to 900s of the 3600s of remaining time (25%).
2024-06-23 08:29:08,120	INFO util.py:124 -- Outdated packages:
  ipywidgets==7.7.1 found, needs ipywidgets>=8
Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.
	Running DyStack sub-fit in a ray process to avoid memory leakage. Enabling ray logging (enable_ray_logging=True). Specify `ds_args={'enable_ray_logging': False}` if you experience logging issues.
2024-06-23 08:29:11,464	INFO worker.py:1743 -- Started a local Ray instance. View the dashboard at 127.0.0.1:8265
		Context path: "AutogluonModels/ag-20240623_082907/ds_sub_fit/sub_fit_ho"
(_dystack pid=489) Running DyStack sub-fit ...
(_dystack pid=489) Beginning AutoGluon training ... Time limit = 895s
(_dystack pid=489) AutoGluon will save models to "AutogluonModels/ag-20240623_082907/ds_sub_fit/sub_fit_ho"
(_dystack pid=489) Train Data Rows:    51806
(_dystack pid=489) Train Data Columns: 71
(_dystack pid=489) Label Column:       price
(_dystack pid=489) Problem Type:       regression
(_dystack pid=489) Preprocessing data ...
(_dystack pid=489) Using Feature Generators to preprocess the data ...
(_dystack pid=489) Fitting AutoMLPipelineFeatureGenerator...
(_dystack pid=489) 	Available Memory:                    29699.59 MB
(_dystack pid=489) 	Train Data (Original)  Memory Usage: 28.06 MB (0.1% of available memory)
(_dystack pid=489) 	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
(_dystack pid=489) 	Stage 1 Generators:
(_dystack pid=489) 		Fitting AsTypeFeatureGenerator...
(_dystack pid=489) 			Note: Converting 66 features to boolean dtype as they only contain 2 unique values.
(_dystack pid=489) 	Stage 2 Generators:
(_dystack pid=489) 		Fitting FillNaFeatureGenerator...
(_dystack pid=489) 	Stage 3 Generators:
(_dystack pid=489) 		Fitting IdentityFeatureGenerator...
(_dystack pid=489) 	Stage 4 Generators:
(_dystack pid=489) 		Fitting DropUniqueFeatureGenerator...
(_dystack pid=489) 	Stage 5 Generators:
(_dystack pid=489) 		Fitting DropDuplicatesFeatureGenerator...
(_dystack pid=489) 	Unused Original Features (Count: 10): ['brand_FIAT', 'brand_Karma', 'brand_Lotus', 'brand_Lucid', 'brand_Maybach', 'brand_Polestar', 'brand_Rivian', 'brand_Saab', 'brand_Suzuki', 'brand_smart']
(_dystack pid=489) 		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
(_dystack pid=489) 		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
(_dystack pid=489) 		These features do not need to be present at inference time.
(_dystack pid=489) 		('float', []) : 10 | ['brand_FIAT', 'brand_Karma', 'brand_Lotus', 'brand_Lucid', 'brand_Maybach', ...]
(_dystack pid=489) 	Types of features in original data (raw dtype, special dtypes):
(_dystack pid=489) 		('float', []) : 58 | ['milage', 'transmission', 'HP', 'Volume', 'age', ...]
(_dystack pid=489) 		('int', [])   :  3 | ['accident', 'is_auto', 'is_manual']
(_dystack pid=489) 	Types of features in processed data (raw dtype, special dtypes):
(_dystack pid=489) 		('float', [])     :  5 | ['milage', 'transmission', 'HP', 'Volume', 'age']
(_dystack pid=489) 		('int', ['bool']) : 56 | ['accident', 'is_auto', 'is_manual', 'brand_Acura', 'brand_Alfa', ...]
(_dystack pid=489) 	1.4s = Fit runtime
(_dystack pid=489) 	61 features in original data used to generate 61 features in processed data.
(_dystack pid=489) 	Train Data (Processed) Memory Usage: 4.74 MB (0.0% of available memory)
(_dystack pid=489) Data preprocessing and feature engineering runtime = 1.47s ...
(_dystack pid=489) AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
(_dystack pid=489) 	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
(_dystack pid=489) 	To change this, specify the eval_metric parameter of Predictor()
(_dystack pid=489) Large model count detected (112 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
(_dystack pid=489) User-specified model hyperparameters to be fit:
(_dystack pid=489) {
(_dystack pid=489) 	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
(_dystack pid=489) 	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
(_dystack pid=489) 	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
(_dystack pid=489) 	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
(_dystack pid=489) 	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
(_dystack pid=489) 	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
(_dystack pid=489) 	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
(_dystack pid=489) 	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
(_dystack pid=489) }
(_dystack pid=489) AutoGluon will fit 2 stack levels (L1 to L2) ...
(_dystack pid=489) Fitting 108 L1 models ...
(_dystack pid=489) Fitting model: KNeighborsUnif_BAG_L1 ... Training model for up to 595.3s of the 893.15s of remaining time.
(_dystack pid=489) 	-15121.9129	 = Validation score   (-root_mean_squared_error)
(_dystack pid=489) 	1.21s	 = Training   runtime
(_dystack pid=489) 	0.42s	 = Validation runtime
(_dystack pid=489) Fitting model: KNeighborsDist_BAG_L1 ... Training model for up to 593.62s of the 891.47s of remaining time.
(_dystack pid=489) 	-15711.2792	 = Validation score   (-root_mean_squared_error)
(_dystack pid=489) 	0.06s	 = Training   runtime
(_dystack pid=489) 	0.42s	 = Validation runtime
(_dystack pid=489) Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 593.1s of the 890.96s of remaining time.
(_dystack pid=489) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=1, gpus=0, memory=0.15%)

(_ray_fit pid=703) [1000]	valid_set's rmse: 13943.2
(_ray_fit pid=907) [1000]	valid_set's rmse: 14174

(_dystack pid=489) 	-13921.3443	 = Validation score   (-root_mean_squared_error)
(_dystack pid=489) 	27.87s	 = Training   runtime
(_dystack pid=489) 	3.76s	 = Validation runtime
(_dystack pid=489) Fitting model: LightGBM_BAG_L1 ... Training model for up to 561.37s of the 859.22s of remaining time.
(_dystack pid=489) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=1, gpus=0, memory=0.15%)

(_ray_fit pid=1156) [1000]	valid_set's rmse: 14125.5

(_dystack pid=489) 	-13878.0493	 = Validation score   (-root_mean_squared_error)
(_dystack pid=489) 	20.83s	 = Training   runtime
(_dystack pid=489) 	2.25s	 = Validation runtime
(_dystack pid=489) Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 536.59s of the 834.44s of remaining time.
(_dystack pid=489) 	-14573.1522	 = Validation score   (-root_mean_squared_error)
(_dystack pid=489) 	46.61s	 = Training   runtime
(_dystack pid=489) 	2.98s	 = Validation runtime
(_dystack pid=489) Fitting model: CatBoost_BAG_L1 ... Training model for up to 485.83s of the 783.68s of remaining time.
(_dystack pid=489) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=1, gpus=0, memory=0.19%)
(_dystack pid=489) 	-13871.5481	 = Validation score   (-root_mean_squared_error)
(_dystack pid=489) 	80.1s	 = Training   runtime
(_dystack pid=489) 	0.2s	 = Validation runtime
(_dystack pid=489) Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 402.55s of the 700.41s of remaining time.
(_dystack pid=489) 	-14534.8767	 = Validation score   (-root_mean_squared_error)
(_dystack pid=489) 	29.58s	 = Training   runtime
(_dystack pid=489) 	2.87s	 = Validation runtime
(_dystack pid=489) Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 368.94s of the 666.79s of remaining time.
(_dystack pid=489) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=1, gpus=0, memory=0.19%)
(_dystack pid=489) 	-14095.2933	 = Validation score   (-root_mean_squared_error)
(_dystack pid=489) 	190.27s	 = Training   runtime
(_dystack pid=489) 	1.31s	 = Validation runtime
(_dystack pid=489) Fitting model: XGBoost_BAG_L1 ... Training model for up to 175.09s of the 472.95s of remaining time.
(_dystack pid=489) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=1, gpus=0, memory=0.23%)
(_dystack pid=489) 	-13864.2083	 = Validation score   (-root_mean_squared_error)
(_dystack pid=489) 	32.2s	 = Training   runtime
(_dystack pid=489) 	1.06s	 = Validation runtime
(_dystack pid=489) Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 138.37s of the 436.23s of remaining time.
(_dystack pid=489) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=1, gpus=0, memory=0.11%)
(_ray_fit pid=2215) 	Ran out of time, stopping training early. (Stopping on epoch 22)
(_ray_fit pid=2346) 	Ran out of time, stopping training early. (Stopping on epoch 22) [repeated 4x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/ray-logging.html#log-deduplication for more options.)
(_dystack pid=489) 	-14312.0235	 = Validation score   (-root_mean_squared_error)
(_dystack pid=489) 	119.75s	 = Training   runtime
(_dystack pid=489) 	0.54s	 = Validation runtime
(_dystack pid=489) Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 15.4s of the 313.26s of remaining time.
(_dystack pid=489) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=1, gpus=0, memory=0.27%)
(_dystack pid=489) 	-13863.187	 = Validation score   (-root_mean_squared_error)
(_dystack pid=489) 	21.21s	 = Training   runtime
(_dystack pid=489) 	1.83s	 = Validation runtime
(_ray_fit pid=2347) 	Ran out of time, stopping training early. (Stopping on epoch 23) [repeated 3x across cluster]
(_dystack pid=489) Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.0s of the 288.11s of remaining time.
(_dystack pid=489) 	Ensemble Weights: {'XGBoost_BAG_L1': 0.32, 'RandomForestMSE_BAG_L1': 0.16, 'CatBoost_BAG_L1': 0.12, 'LightGBM_BAG_L1': 0.08, 'NeuralNetFastAI_BAG_L1': 0.08, 'NeuralNetTorch_BAG_L1': 0.08, 'LightGBMLarge_BAG_L1': 0.08, 'KNeighborsDist_BAG_L1': 0.04, 'LightGBMXT_BAG_L1': 0.04}
(_dystack pid=489) 	-13753.3648	 = Validation score   (-root_mean_squared_error)
(_dystack pid=489) 	0.08s	 = Training   runtime
(_dystack pid=489) 	0.0s	 = Validation runtime
(_dystack pid=489) Fitting 106 L2 models ...
(_dystack pid=489) Fitting model: LightGBMXT_BAG_L2 ... Training model for up to 288.0s of the 287.93s of remaining time.
(_dystack pid=489) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=1, gpus=0, memory=0.20%)
(_dystack pid=489) 	-13776.4501	 = Validation score   (-root_mean_squared_error)
(_dystack pid=489) 	16.61s	 = Training   runtime
(_dystack pid=489) 	0.95s	 = Validation runtime
(_dystack pid=489) Fitting model: LightGBM_BAG_L2 ... Training model for up to 268.04s of the 267.97s of remaining time.
(_dystack pid=489) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=1, gpus=0, memory=0.20%)
(_dystack pid=489) 	-13756.1836	 = Validation score   (-root_mean_squared_error)
(_dystack pid=489) 	16.82s	 = Training   runtime
(_dystack pid=489) 	0.51s	 = Validation runtime
(_dystack pid=489) Fitting model: RandomForestMSE_BAG_L2 ... Training model for up to 247.83s of the 247.76s of remaining time.
(_dystack pid=489) 	-13811.614	 = Validation score   (-root_mean_squared_error)
(_dystack pid=489) 	185.56s	 = Training   runtime
(_dystack pid=489) 	3.58s	 = Validation runtime
(_dystack pid=489) Fitting model: CatBoost_BAG_L2 ... Training model for up to 57.53s of the 57.46s of remaining time.
(_dystack pid=489) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=1, gpus=0, memory=0.25%)
(_dystack pid=489) 	-13756.8997	 = Validation score   (-root_mean_squared_error)
(_dystack pid=489) 	24.58s	 = Training   runtime
(_dystack pid=489) 	0.11s	 = Validation runtime
(_dystack pid=489) Fitting model: ExtraTreesMSE_BAG_L2 ... Training model for up to 29.89s of the 29.82s of remaining time.
(_dystack pid=489) 	Not enough time to generate out-of-fold predictions for model. Estimated time required was 11.28s compared to 10s of available time.
(_dystack pid=489) 	Time limit exceeded... Skipping ExtraTreesMSE_BAG_L2.
(_dystack pid=489) Fitting model: WeightedEnsemble_L3 ... Training model for up to 360.0s of the -20.7s of remaining time.
(_dystack pid=489) 	Ensemble Weights: {'RandomForestMSE_BAG_L2': 0.391, 'LightGBM_BAG_L2': 0.174, 'XGBoost_BAG_L1': 0.13, 'NeuralNetTorch_BAG_L1': 0.087, 'CatBoost_BAG_L2': 0.087, 'RandomForestMSE_BAG_L1': 0.043, 'CatBoost_BAG_L1': 0.043, 'LightGBMXT_BAG_L2': 0.043}
(_dystack pid=489) 	-13690.0256	 = Validation score   (-root_mean_squared_error)
(_dystack pid=489) 	0.12s	 = Training   runtime
(_dystack pid=489) 	0.0s	 = Validation runtime
(_dystack pid=489) AutoGluon training complete, total runtime = 915.49s ... Best model: WeightedEnsemble_L3 | Estimated inference throughput: 469.1 rows/s (6476 batch size)
(_dystack pid=489) TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20240623_082907/ds_sub_fit/sub_fit_ho")
(_dystack pid=489) Deleting DyStack predictor artifacts (clean_up_fits=True) ...
Leaderboard on holdout data (DyStack):
                     model  score_holdout     score_val              eval_metric  pred_time_test  pred_time_val    fit_time  pred_time_test_marginal  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0      WeightedEnsemble_L2  -13841.865457 -13753.364808  root_mean_squared_error       11.259760      14.353754  538.987901                 0.006438                0.001049           0.083881            2       True         12
1          CatBoost_BAG_L2  -13859.538654 -13756.899723  root_mean_squared_error       12.650808      17.752330  594.275074                 0.083541                0.110142          24.580431            2       True         16
2        LightGBMXT_BAG_L2  -13868.906467 -13776.450070  root_mean_squared_error       12.739719      18.589127  586.304804                 0.172451                0.946938          16.610161            2       True         13
3      WeightedEnsemble_L3  -13883.828623 -13690.025628  root_mean_squared_error       14.299118      22.799999  813.372736                 0.007215                0.001083           0.117314            3       True         17
4          LightGBM_BAG_L2  -13896.921983 -13756.183584  root_mean_squared_error       12.734530      18.156877  586.509811                 0.167263                0.514688          16.815168            2       True         14
5          CatBoost_BAG_L1  -13915.847843 -13871.548064  root_mean_squared_error        0.612370       0.200548   80.100361                 0.612370                0.200548          80.100361            1       True          6
6           XGBoost_BAG_L1  -13931.999188 -13864.208285  root_mean_squared_error        0.507751       1.061532   32.203240                 0.507751                1.061532          32.203240            1       True          9
7     LightGBMLarge_BAG_L1  -13935.533717 -13863.187013  root_mean_squared_error        0.495047       1.830484   21.210786                 0.495047                1.830484          21.210786            1       True         11
8          LightGBM_BAG_L1  -13952.466796 -13878.049288  root_mean_squared_error        0.615159       2.252645   20.829645                 0.615159                2.252645          20.829645            1       True          4
9        LightGBMXT_BAG_L1  -13959.297336 -13921.344336  root_mean_squared_error        2.858423       3.760929   27.868973                 2.858423                3.760929          27.868973            1       True          3
10  NeuralNetFastAI_BAG_L1  -14055.930228 -14095.293312  root_mean_squared_error        4.687814       1.306339  190.269911                 4.687814                1.306339         190.269911            1       True          8
11  RandomForestMSE_BAG_L2  -14066.928885 -13811.614039  root_mean_squared_error       13.868648      21.227147  755.249662                 1.301381                3.584959         185.555019            2       True         15
12   NeuralNetTorch_BAG_L1  -14285.390664 -14312.023506  root_mean_squared_error        0.214375       0.537524  119.754951                 0.214375                0.537524         119.754951            1       True         10
13    ExtraTreesMSE_BAG_L1  -14579.429631 -14534.876748  root_mean_squared_error        1.203914       2.874122   29.583569                 1.203914                2.874122          29.583569            1       True          7
14  RandomForestMSE_BAG_L1  -14617.052423 -14573.152167  root_mean_squared_error        1.210526       2.984105   46.605421                 1.210526                2.984105          46.605421            1       True          5
15   KNeighborsUnif_BAG_L1  -15186.509025 -15121.912890  root_mean_squared_error        0.110031       0.415361    1.207053                 0.110031                0.415361           1.207053            1       True          1
16   KNeighborsDist_BAG_L1  -15846.237235 -15711.279195  root_mean_squared_error        0.051857       0.418599    0.060733                 0.051857                0.418599           0.060733            1       True          2
	0	 = Optimal   num_stack_levels (Stacked Overfitting Occurred: True)
	938s	 = DyStack   runtime |	2662s	 = Remaining runtime
Starting main fit with num_stack_levels=0.
	For future fit calls on this dataset, you can skip DyStack to save time: `predictor.fit(..., dynamic_stacking=False, num_stack_levels=0)`
Beginning AutoGluon training ... Time limit = 2662s
AutoGluon will save models to "AutogluonModels/ag-20240623_082907"
Train Data Rows:    58282
Train Data Columns: 71
Label Column:       price
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    29259.64 MB
	Train Data (Original)  Memory Usage: 31.57 MB (0.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 66 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Unused Original Features (Count: 8): ['brand_Lucid', 'brand_Maybach', 'brand_Plymouth', 'brand_Polestar', 'brand_Saab', 'brand_Scion', 'brand_Suzuki', 'brand_smart']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('float', []) : 8 | ['brand_Lucid', 'brand_Maybach', 'brand_Plymouth', 'brand_Polestar', 'brand_Saab', ...]
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 60 | ['milage', 'transmission', 'HP', 'Volume', 'age', ...]
		('int', [])   :  3 | ['accident', 'is_auto', 'is_manual']
	Types of features in processed data (raw dtype, special dtypes):
		('float', [])     :  5 | ['milage', 'transmission', 'HP', 'Volume', 'age']
		('int', ['bool']) : 58 | ['accident', 'is_auto', 'is_manual', 'brand_Acura', 'brand_Alfa', ...]
	1.7s = Fit runtime
	63 features in original data used to generate 63 features in processed data.
	Train Data (Processed) Memory Usage: 5.45 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 1.82s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Large model count detected (112 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 108 L1 models ...
Fitting model: KNeighborsUnif_BAG_L1 ... Training model for up to 2660.3s of the 2660.28s of remaining time.
	-15122.2522	 = Validation score   (-root_mean_squared_error)
	0.28s	 = Training   runtime
	0.39s	 = Validation runtime
Fitting model: KNeighborsDist_BAG_L1 ... Training model for up to 2659.58s of the 2659.57s of remaining time.
	-15727.6492	 = Validation score   (-root_mean_squared_error)
	0.05s	 = Training   runtime
	0.38s	 = Validation runtime
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 2659.12s of the 2659.11s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=1, gpus=0, memory=0.15%)
	-13921.3043	 = Validation score   (-root_mean_squared_error)
	27.35s	 = Training   runtime
	4.78s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 2628.04s of the 2628.03s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=1, gpus=0, memory=0.16%)
	-13877.9667	 = Validation score   (-root_mean_squared_error)
	22.12s	 = Training   runtime
	2.96s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 2602.3s of the 2602.28s of remaining time.
	-14543.8942	 = Validation score   (-root_mean_squared_error)
	50.85s	 = Training   runtime
	3.36s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 2546.94s of the 2546.93s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=1, gpus=0, memory=0.19%)
	-13848.3746	 = Validation score   (-root_mean_squared_error)
	106.54s	 = Training   runtime
	0.23s	 = Validation runtime
Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 2437.3s of the 2437.29s of remaining time.
	-14488.3146	 = Validation score   (-root_mean_squared_error)
	32.33s	 = Training   runtime
	3.28s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 2400.55s of the 2400.54s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=1, gpus=0, memory=0.20%)
	-14304.5837	 = Validation score   (-root_mean_squared_error)
	206.02s	 = Training   runtime
	1.27s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 2191.03s of the 2191.01s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=1, gpus=0, memory=0.24%)
	-13867.7467	 = Validation score   (-root_mean_squared_error)
	38.78s	 = Training   runtime
	1.21s	 = Validation runtime
Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 2148.4s of the 2148.38s of remaining time.

In [55]:
x = the_train.drop(columns=['price'])
y = the_train['price']

In [56]:
x

,milage,transmission,accident,HP,Volume,age,is_auto,is_manual,brand_Acura,brand_Alfa,brand_Aston,brand_Audi,brand_BMW,brand_Bentley,brand_Bugatti,brand_Buick,brand_Cadillac,brand_Chevrolet,brand_Chrysler,brand_Dodge,brand_FIAT,brand_Ferrari,brand_Ford,brand_GMC,brand_Genesis,brand_Honda,brand_Hummer,brand_Hyundai,brand_INFINITI,brand_Jaguar,brand_Jeep,brand_Karma,brand_Kia,brand_Lamborghini,brand_Land,brand_Lexus,brand_Lincoln,brand_Lotus,brand_Lucid,brand_MINI,brand_Maserati,brand_Maybach,brand_Mazda,brand_McLaren,brand_Mercedes-Benz,brand_Mercury,brand_Mitsubishi,brand_Nissan,brand_Plymouth,brand_Polestar,brand_Pontiac,brand_Porsche,brand_RAM,brand_Rivian,brand_Rolls-Royce,brand_Saab,brand_Saturn,brand_Scion,brand_Subaru,brand_Suzuki,brand_Tesla,brand_Toyota,brand_Volkswagen,brand_Volvo,brand_smart,fuel_type_Diesel,fuel_type_E85 Flex Fuel,fuel_type_Electric,fuel_type_Gasoline,fuel_type_Hybrid,fuel_type_Plug-In Hybrid
0,0.133082,1.173740,0,0.511811,0.0000,-0.285714,1,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,0.213523,0.000000,0,-0.078740,-0.3125,1.285714,0,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,0.377096,-0.416022,0,-0.078740,0.4375,1.000000,1,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,-0.890577,0.546557,0,0.196850,-0.3125,-0.857143,1,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.654804,-0.188390,0,-0.866142,0.1875,2.142857,1,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58277,0.000000,6.473700,0,0.000000,1.5625,-1.000000,1,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
58278,-0.770107,0.546557,0,0.307087,-0.3125,-0.857143,1,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
58279,-0.895146,1.132466,0,0.000000,0.0000,-0.857143,1,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
58280,-0.455516,-0.188390,0,1.102362,0.0000,-0.571429,1,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
58281,-0.313167,-0.188390,1,-0.488189,-0.9375,-0.571429,1,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [57]:
y

0        11000.0
1         8250.0
2        15000.0
3        63500.0
4         7850.0
          ...
58277    90802.5
58278    53900.0
58279    90802.5
58280    62999.0
58281    40000.0
Name: price, Length: 58282, dtype: float64

In [58]:
y_pred = gluon_automl.predict(x)

In [61]:
from sklearn.metrics import mean_squared_error
train_rmse = np.sqrt(mean_squared_error(y, y_pred))
train_rmse

11346.309032820758

In [62]:
kaggle_predictions = gluon_automl.predict(test)

In [63]:
sub_df = pd.DataFrame({
    'id':kaggle_ids,
    'price':kaggle_predictions
})
sub_df

          id         price
0      54273  20871.142578
1      54274  22929.753906
2      54275  26838.988281
3      54276  55598.578125
4      54277  34370.800781
...      ...           ...
36178  90451  58000.734375
36179  90452  10018.360352
36180  90453  10823.953125
36181  90454  55057.878906
36182  90455  13343.654297

[36183 rows x 2 columns]

In [65]:
sub_df.to_csv('sub_ag.csv', index=False)